# Generated by Django 4.0 on 2023-02-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='planAnswer',
            field=models.CharField(default='cevap', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='unCurrectAnswer',
            field=models.CharField(default='cevap', max_length=500),
            preserve_default=False,
        ),
    ]
