# Generated by Django 4.0 on 2023-03-02 11:41

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_question_currect'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='tml',
            field=models.FileField(blank=True, default=None, null=True, upload_to=api.models.upload_path),
        ),
        migrations.AddField(
            model_name='files',
            name='yetki_belgesi',
            field=models.FileField(blank=True, default=None, null=True, upload_to=api.models.upload_path),
        ),
        migrations.AddField(
            model_name='files',
            name='yillik_rapor',
            field=models.FileField(blank=True, default=None, null=True, upload_to=api.models.upload_path),
        ),
    ]
