# Generated by Django 4.2.6 on 2023-12-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_files_tml_files_yetki_belgesi_files_yillik_rapor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answerA',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answerB',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answerC',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='currect',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='currectAnswer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='planAnswer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionText',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='subCategory',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='unCurrectAnswer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
