# Generated by Django 4.2.6 on 2023-12-06 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_question_answera_alter_question_answerb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='currect',
        ),
    ]
