# Generated by Django 4.2.6 on 2023-12-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_question_currect'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='otherCurrectAnswer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
